server:
  port: 8761

management:
  context-path: /admin

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  server:
    waitTimeInMsWhenSyncEmpty: 0

#TODO: move to eureka
spring:
  boot:
    admin:
      url: http://localhost:8080
    